(defun radd-count-words()
  (interactive)
  (setq words 0)
  (setq position (point))
  (while (search-forward "\\radd{" nil t)
    (setq list 1)
    (setq counter 0)
    (while (> list 0)
      (setq counter (1+ counter))
      (goto-char (+ (point) 1))
      (when (string= "}" (char-to-string (char-after)))
	(setq list (1- list))
	)
      (when (string= "{" (char-to-string (char-after)))
	(setq list (1+ list))
	)
      )
    (setq words (+ words counter))
    )
  (print words)
  (goto-char position)
  (insert (int-to-string words))
  )
